### ISSUE TITLE
Setting games directory as root of drive causes crash

### ISSUE THREAD

**Issue by Neodymium5312** [Ryujinx/Ryujinx#1019]
If you set the root of a drive as the games directory Ryujinx will crash at boot with errors in the log. 

The emulator will immediately crash after hitting "save"

This is a seperate drive attatched to my computer, it is a Samsung SSD connected over SATA3, the drive is empty besides my games, I have access to the drive from windows without any issues, and do not need admin perms to read/write to the drive.
[Ryujinx_2020-03-23_23-40-37.log](https://github.com/Ryujinx/Ryujinx/files/4373215/Ryujinx_2020-03-23_23-40-37.log)

This cannot be fixed unless the config.json is either deleted or manually edited to remove the game directory setting as ryujinx refuses to boot completely and just crashes at startup.

**Comment by Neodymium5312** [comment]
Unhandled exception caught: System.UnauthorizedAccessException: Access to the path 'E:\System Volume Information' is denied.

I don't know why it would attempt to open the svi but that seems to be whats causing this issue is reading the hidden system files on the root of the drive

**Comment by Sch1nken** [comment]
Had a similar thing though in "D:\switchgames". For my particular path I got no idea (though I was getting a JSON parse error -> "expected { but found ' ") but for you it might be looking recursively and accessing that folder?

**Comment by EliseZeroTwo** [comment]
Submitted a pull request that should fix this issue

**Comment by duriumm** [comment]
This is still occurring and is not yet fixed. Is there a fix for this? :)
