### ISSUE TITLE
Kirby star allies : Resolution scaling reset by itself to native after 2-3 mins of gameplay

### ISSUE THREAD

**Issue by c3ntrin0** [Ryujinx/Ryujinx#2439]
### What's the issue you encountered?

During initial gameplay , resolution scaling works very well.
After 2-3 mins of gameplay, suddenly it revert back to native resolution by itself. 

### How can the issue be reproduced?

Play the game with resolution scaling on (x2 or above) , handheld or docked mode give similar result.

### Environment?

- Ryujinx version: 1.0.6945</br>
- Game version: 4.0.0</br>
  - OS: win10
  - CPU: i7-10700k
  - GPU: RTX3070
  - RAM: *16gb
- Applied Mods : no

### Additional context?

https://www.youtube.com/watch?v=mj6_eIIS2Zw&t=161s
[res scaling works.zip](https://github.com/Ryujinx/Ryujinx/files/6757488/res.scaling.works.zip)
[res scaling reset by itself.zip](https://github.com/Ryujinx/Ryujinx/files/6757489/res.scaling.reset.by.itself.zip)

**Comment by GamerzHell9137** [comment]
@c3ntrin0 Can you check if https://github.com/Ryujinx/Ryujinx/pull/2860 fixes it?

**Comment by Shahil-Ayato** [comment]
I believe this has been solved as I haven’t been able to reproduce this so this should be closed.

**Comment by NickHam13** [comment]
Still getting this issue on Master, Vulkan PR and #2860. The resolution resets when you use a copy ability with an elemental ability attached to it. An easy way to reproduce is to go to the start of level 2, there's a sword and water enemy to test this with.

**Comment by benderscruffy** [comment]
Close this as now only tracking game-specific issues on the compatibility list. Thanks.

**Comment by MetrosexualGarbodor** [comment]
Please post about this in #1488 if it still occurs.
