### ISSUE TITLE
[Regression][Linux] Broken input in docked mode

### ISSUE THREAD

**Issue by A-w-x** [Ryujinx/Ryujinx#2806]
### What's the issue you encountered?

Tested this in pokemon sw/sh.

boot in handheld mode.
enable player 1 input (any type)
Switch to docked mode and input will go crazy.

### Environment?

- Ryujinx version: 1.0.7096</br>
- System Specs:
  - OS: *ArchLinux*
  - CPU: *i5-1035g7*
  - GPU: *iris plus 940*
  - RAM: *16gb*
- Applied Mods : no

**Comment by B3astTech** [comment]
## Bug Report

### What's the issue you encountered?

I could not Reproduce this issue on Build 1.1.7.
It was either fixed at some point.

[Ryujinx_1.1.7 Sword Input.log](https://github.com/Ryujinx/Ryujinx/files/7928055/Ryujinx_1.1.7.Sword.Input.log)

### Environment?

- Ryujinx version: 1.1.7</br>
- Game version: 1.0.0</br>

- System Specs:
  - OS: *Fedora 35*
  - CPU: *i7-2600k*
  - GPU: *1050ti*
  - RAM: *16GB*
- Applied Mods : [N/A]

**Comment by A-w-x** [comment]
still happening on 1.1.15 and just found whats wrong

my settings:

player 1: xbox 360 controller as pro controller
handheld: xbox 360 controller

ryujinx goes crazy when the same controller is enabled in both player X and handheld, it should instead ignore inputs from handheld in docked mode
