### ISSUE TITLE
Minecraft [0100d71004694000] Crashing on world load

### ISSUE THREAD

**Issue by piplup55** [Ryujinx/Ryujinx#3236]
### What's the issue you encountered?

Minecraft Crashing when loading/Making a world

### How can the issue be reproduced?

Open minecraft and try and load or make a new world

### Log file

[Ryujinx_1.1.85_2022-03-27_18-42-02.log](https://github.com/Ryujinx/Ryujinx/files/8358159/Ryujinx_1.1.85_2022-03-27_18-42-02.log)

### Environment?

- Ryujinx version: 1.1.85
- Game version: 1.0.0

- System Specs:
  - OS: EndeavourOS
  - CPU: Ryzen 7 3700X
  - GPU: NVIDIA GTX 1050
  - RAM: 64GB

- Applied Mods : no

### Additional context?

Last known working version is 1.0.7181

**Comment by MetrosexualGarbodor** [comment]
This and #3237 seem to have the same error.

**Comment by MutantAura** [comment]
Mario Odyssey online mod also seems to have the same error. 
Log:
[Ryujinx_1.1.150_2022-06-18_10-28-14.log](https://github.com/Ryujinx/Ryujinx/files/8934002/Ryujinx_1.1.150_2022-06-18_10-28-14.log)

I'm also updating this issue's title and content to include #3237 as they all seem to have stopped working at the same time so likely same issue.

**Comment by piplup55** [comment]
ever since [SMOO PR 23](https://github.com/CraftyBoss/SuperMarioOdysseyOnline/pull/23) Super Mario Odyssey should work if you build from the dev branch

**Comment by piplup55** [comment]
minecraft now goes in game, other games in this issue needs retesting
![image](https://user-images.githubusercontent.com/100526773/200086240-6d963b9b-a5e6-42fb-8bc2-a17ee9f009dc.png)

**Comment by TSRBerry** [comment]
I believe this was already mentioned in the [progress report](https://blog.ryujinx.org/progress-report-august-2022/) for august.
Minecraft made me aware of the issue that was fixed with #3633

**Comment by piplup55** [comment]
> I believe this was already mentioned in the [progress report](https://blog.ryujinx.org/progress-report-august-2022/) for august. Minecraft made me aware of the issue that was fixed with #3633

this is true, but i never posted a comment on this so i did it for the sake of anyone looking at this who might not know

**Comment by MarkLanders777** [comment]
> minecraft now goes in game, other games in this issue needs retesting ![image](https://user-images.githubusercontent.com/100526773/200086240-6d963b9b-a5e6-42fb-8bc2-a17ee9f009dc.png)

That update is not the last official update (1.19.40), which still crashes the emu, Minecraft just runs in 1.0 (base game) and update 1.12.xx

**Comment by TSRBerry** [comment]
Is it the same issue? Or another one?

**Comment by piplup55** [comment]
> Is it the same issue? Or another one?

different, iirc it just won't load you into a world

**Comment by MarkLanders777** [comment]
> > Is it the same issue? Or another one?
> 
> different, iirc it just won't load you into a world

Invalid memory access, so, it's a different one

**Comment by MarkLanders777** [comment]
> > Is it the same issue? Or another one?
> 
> different, iirc it just won't load you into a world

I goes until title screen, then throws a invalid memory access and crashes
