### ISSUE TITLE
Super mario 3d world + Bowser's Fury failed to load with Font error 

### ISSUE THREAD

**Issue by bback99** [Ryujinx/Ryujinx#3278]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]

### What's the issue you encountered?

Ryujinx version(1.1.103) has crashed suddenly durinig playing the game(3d world mode)
but Bowser's Fury mode is working well

### How can the issue be reproduced?

after choose any characters in 3d world mode then crashed while loading for the next step

### Log file

00:00:40.445 |E| HLE.OsThread.16 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: None of these fonts were found in the system: 맑은 고딕, Liberation Sans, FreeSans, DejaVu Sans!
   at Ryujinx.HLE.HOS.Applets.SoftwareKeyboard.SoftwareKeyboardRendererBase.CreateFonts(String uiThemeFontFamily) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Applets\SoftwareKeyboard\SoftwareKeyboardRendererBase.cs:line 137
   at Ryujinx.HLE.HOS.Applets.SoftwareKeyboard.SoftwareKeyboardRendererBase..ctor(IHostUiTheme uiTheme) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Applets\SoftwareKeyboard\SoftwareKeyboardRendererBase.cs:line 107
   at Ryujinx.HLE.HOS.Applets.SoftwareKeyboard.SoftwareKeyboardRenderer..ctor(IHostUiTheme uiTheme) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Applets\SoftwareKeyboard\SoftwareKeyboardRenderer.cs:line 26
   at Ryujinx.HLE.HOS.Applets.SoftwareKeyboardApplet.Start(AppletSession normalSession, AppletSession interactiveSession) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Applets\SoftwareKeyboard\SoftwareKeyboardApplet.cs:line 105
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 122
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 214
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 133
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1263
### Environment?

- Ryujinx version: 1.1.103</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 1.0.0</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: Windows 10 Pro/OS build: 19044.1586 / Version: 21H2 
  - CPU: i5-4690K
  - GPU: NVIDIA GeForce GTX 750 Ti
  - RAM: 8GB
- Applied Mods : [ Yes (Which ones) / No ]

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by MetrosexualGarbodor** [comment]
This issue would probably be fixed by #2998, sadly that pull request has been closed.

**Comment by kode54** [comment]
This still happens. It manages to crash the emulator on Windows.

**Comment by alucaltair** [comment]
> This still happens. It manages to crash the emulator on Windows. Just starting the game in 2 player mode, Windows 11, Nvidia RTX 3060 12GB. Further edit: This appears to be a different issue. Ours was also font related, but some third party software was involved.

hey! 
do you found some fix about it? 
i got same problem here 

---> System.Exception: None of these fonts were found in the system: Segoe UI, Liberation Sans, FreeSans, DejaVu Sans, Lucida Grande!
   at Ryujinx.HLE.HOS.Applets.SoftwareKeyboard.SoftwareKeyboardRendererBase.CreateFonts(String uiThemeFontFamily)
   at Ryujinx.HLE.HOS.Applets.SoftwareKeyboard.SoftwareKeyboardRendererBase..ctor(IHostUiTheme uiTheme)
   at Ryujinx.HLE.HOS.Applets.SoftwareKeyboard.SoftwareKeyboardRenderer..ctor(IHostUiTheme uiTheme)
   at Ryujinx.HLE.HOS.Applets.SoftwareKeyboardApplet.Start(AppletSession normalSession, AppletSession interactiveSession)
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.LibraryAppletCreator.ILibraryAppletAccessor.Start(ServiceCtx context)
   at System.RuntimeMethodHandle.InvokeMethod(Object, Void**, Signature, Boolean)
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
   at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context)
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr)
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop()
   at Ryujinx.HLE.HOS.Services.ServerBase.Main()
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()

**Comment by kddlb** [comment]
The issue that @kode54 mentioned was that I was using StartAllBack with the "Use new font for classic UI" option enabled, which set the UI shell font to "Segoe UI Variable Text," which I think GTK can't locate...

**Comment by alucaltair** [comment]
> The issue that @kode54 mentioned was that I was using StartAllBack with the "Use new font for classic UI" option enabled, which set the UI shell font to "Segoe UI Variable Text," which I think GTK can't locate...

I just installed StartAllBack and enabled the classic UI option but doesn't works still font error, any other idea to try fix it?

Thank by the way for your help

**Comment by kode54** [comment]
We were reporting that enabling that option is what caused the problem for us. The root issue may be something else entirely in your case.

**Comment by MetrosexualGarbodor** [comment]
Apparently the Avalonia GUI fixes this issue, as per another user on discord. If anyone is still having it, I would appreciate it if they could test an Avalonia build and report back if it works or not.

Avalonia builds can be found [here](https://github.com/Ryujinx/release-channel-master/releases), named `test-ava-ryujinx`.
