### ISSUE TITLE
Xenoblade Chronicles 3 [010074F013262000]: Vulkan backend crashes before title screen on AMD

### ISSUE THREAD

**Issue by rabidcopy** [Ryujinx/Ryujinx#3513]
### What's the issue you encountered?

Game fails to reach the title screen when using the Vulkan backend. Have tried 1x resolution, 2x resolution, clearing caches, clearing the Ryujinx folder and starting with fresh defaults.

### How can the issue be reproduced?

Load the game on an AMD GPU with the Vulkan backend option selected.

### Log file

[Ryujinx_1.1.200_2022-07-31_19-06-06.log](https://github.com/Ryujinx/Ryujinx/files/9229985/Ryujinx_1.1.200_2022-07-31_19-06-06.log)

Last bit of the logging console before Ryujinx closes if it's any help.

<img width="663" alt="console" src="https://user-images.githubusercontent.com/8052832/182051299-b7ae2dd7-9fb6-452e-90ce-d92e69cd21ff.png">

### Environment?

- Ryujinx version: 1.1.200</br>
- Game version: 1.0.0-1.1.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 2600
  - GPU: AMD RX 570
  - GPU Driver: AMD Software: Adrenalin Edition 22.7.1
  - RAM: 16GB
- Applied Mods : No

### Additional context?

Seems to be the same case when attempting to use the Vulkan backend on Linux with an AMD card as well. But that was with the #2518 PR build earlier today and not the 1.1.200 release. Can provide a log for that as well. I'm suspecting this affects Polaris cards and below after asking around a bit. Edit: Happens on RDNA cards as well apparently.

[Ryujinx_1.1.200_2022-07-31_19-25-50.log](https://github.com/Ryujinx/Ryujinx/files/9230055/Ryujinx_1.1.200_2022-07-31_19-25-50.log)

**Comment by KawaiiDinosaur** [comment]
Same issue on Linux using an AMD GPU with the Vulkan backend.

**Comment by adnan-travar** [comment]
Same thing in my case.

 ### Environment?
 * Ryujinx version: 1.1.200-1.1.2.0.1
 *  Game version: 1.0.0-1.1.0
 * System Specs:
   
   * OS: Windows 11
   * CPU: Ryzen 5800
   * GPU: AMD Vega 64
   * GPU Driver: AMD Software: Adrenalin Edition 22.7.1
   * RAM: 16GB
 * Applied Mods : No

**Comment by rabidcopy** [comment]
Appears to work fine on Windows 10 with an RX 570 with #3529. Linux boots and shows the loading screen, but crashes before reaching the title screen. Have cleared caches, tried 1x and 2x resolution. No mods or cheats loaded
[Ryujinx_1.1.0+d49ad0c_2022-08-04_01-23-33.log](https://github.com/Ryujinx/Ryujinx/files/9257201/Ryujinx_1.1.0%2Bd49ad0c_2022-08-04_01-23-33.log)
.

**Comment by MetrosexualGarbodor** [comment]
Fixed by #3552.

**Comment by Squirrlz** [comment]
Still crashing before title screen on Steam Deck/Linux. Tried with both regular and LDN3.
