### ISSUE TITLE
[Bug] In-game camera doesn't identify targets in Totk

### ISSUE THREAD

**Issue by chromatic91** [Ryujinx/Ryujinx#4942]
### Description of the issue

I've been having a problem since launch with the in-game camera.
It doesn't "identify" what you're aiming it at, which means you cant solve some quests nor fill out your compendium.
After some research with other people having the same issue, switching to OpenGL usually solves it, but i'd rather use Vulkan.
I tried searching for a bug report like this, but i'm new here and don't quite understand how Github works.
Feel free to remove my post if i did something wrong!
Hugs

### Reproduction steps

Enable Vulkan renderer
Attempt to photograph a monster or quest item
Then switch to OpenGL and see how it works.

### Log file

[Ryujinx_1.1.797_2023-05-13_11-24-13.log](https://github.com/Ryujinx/Ryujinx/files/11471528/Ryujinx_1.1.797_2023-05-13_11-24-13.log)

### OS

Windows 10

### Ryujinx version

1.1.799

### Game version

1.10

### CPU

i7 8700k

### GPU

Nvidia 1080 ti

### RAM

32 gb

**Comment by gr3ger** [comment]
Might want to specify which game you're talking about. I'm gonna assume it's Tears of the Kingdom, but might as well be Breath of the Wild.

**Comment by chromatic91** [comment]
> Might want to specify which game you're talking about. I'm gonna assume it's Tears of the Kingdom, but might as well be Breath of the Wild.

Thanks so much!

**Comment by AcK77** [comment]
Does the issue occur without mods ?

**Comment by chromatic91** [comment]
> Does the issue occur without mods ?

I removed my only mod (30 fps, it wasnt even needed anymore) and it was still there.

**Comment by gr3ger** [comment]
I've been playing several hours on Totk with Vulkan and the in-game camera does correctly identify items for me. (W11, Ryujinx 1.1.800, AMD CPU, Nvidia GPU, game version 1.1.0). Camera tracking seems identical between OpenGL and Vulkan. You do have to get kind of close / zoom in for the game to register though.

**Comment by LoneBoco** [comment]
I had the issue with Yuzu in the Depths when I first got the camera.  I ended up applying the 1.1.0 patch, erased my shader cache, and restarted and it went away.  Seeing that people are experiencing it with Ryujinx too I wonder if it is a bug with the game itself.  Try restarting the game, leaving the depths, clearing your shaders, etc.  Ever since then its worked 100% fine for me.

**Comment by chromatic91** [comment]
> I'm also having this issue, I'm sure it's a bug in Vulkan mode, and when I switch OpenGL, it's gone To add the Win 11 3070GPU 13600K CPU

It seems to only select a fair few people for sure, hence it seems difficult to reproduce. I switched to Yuzu and it works well with both renderers, and a huge performance boost to boot!

**Comment by XIDRM** [comment]
> 

I thought this was a common bug, and yuzu existed in previous versions as well. But the latest version has been fixed

**Comment by XIDRM** [comment]
> > 我也遇到了这个问题，我确定这是 Vulkan 模式下的错误，当我切换 OpenGL 时，它已经消失了 添加 Win 11 3070GPU 13600K CPU
> 
> 它似乎只选择了相当少的人，因此似乎很难繁殖。我切换到 Yuzu，它与两个渲染器配合得很好，并且启动时性能得到了巨大的提升！

I thought this was a common bug, and yuzu existed in previous versions as well. But the latest version has been fixed

**Comment by Destro2hell** [comment]
im having this same issue but when i swap to openGL all i have is a black screen and i have tried almost all fixes and still cant get the black screen to go away

**Comment by gr3ger** [comment]
> I had the issue with Yuzu in the Depths when I first got the camera. I ended up leaving the Depths, applying the 1.1.0 patch, erased my shader cache, and restarted. The problems disappeared. Seeing that people are experiencing it with Ryujinx too I wonder if it is a bug with the game itself. Try restarting the game, leaving the depths, clearing your shaders, etc. Ever since then its worked 100% fine for me on both emulators.

I honestly think this might be the real culprit. I've also cleared shader cache & queued PPTC rebuild once the first batch of TotK specific updates to Ryujinx started landing.
So I would suggest people to make sure they've updated the game to 1.1.0, then clear shader cache and queue a PPTC rebuild and see if the issue persists.

**Comment by worewolf09r** [comment]
Is there a way to get rid of the shades?

**Comment by kaapiel** [comment]
for me the fix was to activate the VSync 🤔

**Comment by sishuiliunian** [comment]
mac m1 pro , after use version 1.1.1281  can "finding" objects to take pictures of。
