### ISSUE TITLE
[Bug] Persona 5 Royal screen flickering since 1.1.1066

### ISSUE THREAD

**Issue by ThePiban** [Ryujinx/Ryujinx#5878]
### Description of the issue

after the update 1.1.1066, theres screen flickering in the overworld especially in the school classroom or cafe leblanc in Persona 5 Royal.
https://www.youtube.com/playlist?list=PLk0QmWe0TzwgsUlweElu_YKGzkSzzZRTM

### Reproduction steps

Loading into areas (especially the two mentioned above)

### Log file

[Ryujinx_1.1.1065_2023-11-02_06-09-34.log](https://github.com/Ryujinx/Ryujinx/files/13231945/Ryujinx_1.1.1065_2023-11-02_06-09-34.log)
[Ryujinx_1.1.1066_2023-11-02_05-59-57.log](https://github.com/Ryujinx/Ryujinx/files/13231946/Ryujinx_1.1.1066_2023-11-02_05-59-57.log)

### OS

MacOS Sonoma

### Ryujinx version

1.1.1066

### Game version

1.0.2

### CPU

m1 base

### GPU

m1 base

### RAM

16gb

**Comment by IsaacMarovitz** [comment]
Should be fixed by #5906

**Comment by ThePiban** [comment]
> Should be fixed by #5909

unfortunately it still occurs..
https://youtu.be/c2SPHMUOb0U

**Comment by ThePiban** [comment]
> > Should be fixed by #5909
> 
> unfortunately it still occurs.. https://youtu.be/c2SPHMUOb0U

sorry that was the wrong version, here's the vid with recent masters which implemented this change
https://www.youtube.com/watch?v=_b5tTAmyew8
