### ISSUE TITLE
[Bug] Fashion Dreamer Unplayable

### ISSUE THREAD

**Issue by Bypnos** [Ryujinx/Ryujinx#5905]
### Description of the issue

The game crashes when exiting the "Pop Up Area" in the beginning of the game, maybe 15-30 minutes into playing. Crashes every time you exit that area, it's a pretty game-ending bug with the way the game is set up, if your save is in there like mine is it just bricks the save. 

There's also a load of missing textures on models that the game doesn't load. 

### Reproduction steps

Play for about 15-30 minutes normally and it'll just happen. 

### Log file

[Ryujinx_1.1.1072_2023-11-08_09-50-35.log](https://github.com/Ryujinx/Ryujinx/files/13299009/Ryujinx_1.1.1072_2023-11-08_09-50-35.log)

### OS

Windows 10

### Ryujinx version

1.1.1072

### Game version

1.1.0

### CPU

AMD Ryzen 5 1600 Six-Core Processor

### GPU

NVIDIA GeForce GTX 1050 Ti

### RAM

16 Gigs

### List of applied mods

None.

### Additional context?

Save File if it makes it easier:

[000000000000000e.zip](https://github.com/Ryujinx/Ryujinx/files/13299104/000000000000000e.zip)

**Comment by Bypnos** [comment]
It might've actually been the "Salon Area" it was crashing on exit, the level all looks the same.

**Comment by Bypnos** [comment]
The game list screen is also completely wrong and says I have 0 playtime in it, and that I've never opened it past the very first time I opened the game. 

 https://media.discordapp.net/attachments/941819158256037908/1171855431602282496/image.png?ex=655e326a&is=654bbd6a&hm=670f889060f7dd2303b99b9d48794209e0fedad40be53aac8d61756750f02b93&=

**Comment by gdkchan** [comment]
Can you check if #5927 fixes the issue?

**Comment by Bypnos** [comment]
A completely different issue arises after the update, the clothes textures have become duplicated in the inventory, overwriting other clothes. Issue does not happen on Yuzu.
![image](https://github.com/Ryujinx/Ryujinx/assets/150274628/aac76307-59ac-4f93-9585-95715b25f86c)

**Comment by gdkchan** [comment]
How does one reproduce that issue? Because I tried opening that menu on the save you provided, and there is no such issue.
Was the issue originally reported fixed?

**Comment by Bypnos** [comment]
I literally just opened the same save, I don't know what to tell you. 
The original issues seems to have been fixed, yes, should I open a different bug thread about it and close this one?

**Comment by gdkchan** [comment]
Please attach the save here if possible. It seems to be different from the one in the first post.

**Comment by ponmono** [comment]
The duplicating item thumbnails issue persists even in 1.1.1083 version under both Vulkan and OpenGL. It is most noticeable in the Item Creator part of the game. Game version is 1.1.0 with 4 DLC installed.

![ryujinx_capture_2023-11-15_16-34-15](https://github.com/Ryujinx/Ryujinx/assets/150879556/f7b16c15-8b0b-461d-b60f-84db063de4bb)

**Comment by Bypnos** [comment]
[000000000000000e.zip](https://github.com/Ryujinx/Ryujinx/files/13359915/000000000000000e.zip)

**Comment by skateser** [comment]
just want to add that i have the same issue. thanks.

**Comment by gdkchan** [comment]
The duplicated item issue has been fixed on emulator version 1.1.1087. Please open a new issue if the problem persists, or you find another issue.
