### ISSUE TITLE
m1 mac crashes all the time recently, used to be stable

### ISSUE THREAD

**Issue by mxradio** [Ryujinx/Ryujinx#6697]
### Description of the issue

ryujinx crashes everytime I use it now, sometimes right away after I start a game sometimes a few minutes in. 

### Reproduction steps

all games crash after a few minutes 

### Log file

[Ryujinx_1.1.1289_2024-04-21_11-37-16.log](https://github.com/Ryujinx/Ryujinx/files/15053104/Ryujinx_1.1.1289_2024-04-21_11-37-16.log)
[Ryujinx_1.1.1289_2024-04-21_11-29-50.log](https://github.com/Ryujinx/Ryujinx/files/15053105/Ryujinx_1.1.1289_2024-04-21_11-29-50.log)
[Ryujinx_1.1.1249_2024-04-21_11-29-20.log](https://github.com/Ryujinx/Ryujinx/files/15053106/Ryujinx_1.1.1249_2024-04-21_11-29-20.log)

### OS

mac os sonoma 14.4.1 

### Ryujinx version

1.1.1289

### CPU

m1 mac

### GPU

silicon gpu

### RAM

32gb

### List of applied mods

none

**Comment by CatMow** [comment]
![image](https://github.com/Ryujinx/Ryujinx/assets/84914492/ac6ba370-c1ba-4562-b9a4-8676b49e2285)
100% a mod issue. 0x0 is invalid in any game.

disable all mods and try again.

**Comment by piplup55** [comment]
> 100% a mod issue. 0x0 is invalid in any game.
> 
> disable all mods and try again.

they have no mods at all

@mxradio can you try the latest version it may have been fixed by #6695

**Comment by mxradio** [comment]
Thanks, I didn't think I had any mods currently installed.

**Comment by mxradio** [comment]
still crashing with #6695. 
[Ryujinx_1.1.0+f6879b1_2024-04-22_13-30-23.log](https://github.com/Ryujinx/Ryujinx/files/15068379/Ryujinx_1.1.0%2Bf6879b1_2024-04-22_13-30-23.log)
[Ryujinx_1.1.0+f6879b1_2024-04-22_13-25-53.log](https://github.com/Ryujinx/Ryujinx/files/15068381/Ryujinx_1.1.0%2Bf6879b1_2024-04-22_13-25-53.log)

**Comment by mxradio** [comment]
Thanks, I'll have to keep notes on which games work with hypervisor or not.

**Comment by mxradio** [comment]
Yoshi's Crafted World crashing now too. 

[Ryujinx_1.1.0+f6879b1_2024-04-27_15-52-42.log](https://github.com/Ryujinx/Ryujinx/files/15140228/Ryujinx_1.1.0%2Bf6879b1_2024-04-27_15-52-42.log)
[Ryujinx_1.1.0+f6879b1_2024-04-27_15-49-45.log](https://github.com/Ryujinx/Ryujinx/files/15140229/Ryujinx_1.1.0%2Bf6879b1_2024-04-27_15-49-45.log)
